export const ROW_DATA = [
  {
    id: 0,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 1,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 2,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 3,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 4,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 5,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 6,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 7,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
  {
    id: 8,
    title: "Oliver Smith",
    date: "Sep 23, 2022",
    author: "William",
    category: "Romance",
    status: "Draft",
  },
];
